### ISSUE TITLE
If the spoke cluster cannot connect to the helm repository, how do I resolve it

### ISSUE THREAD

**Issue by jianglu6** [open-cluster-management-io/multicloud-operators-subscription#28]
if I want to install a helm chart app for spoke cluster, does the action of downloading the Chart package take place on the spoke cluster ? If the spoke cluster cannot connect to the helm repository, how do I resolve it

**Comment by mikeshng** [comment]
>  does the action of downloading the Chart package take place on the spoke cluster ? 
Yes.

It's currently our design for spoke clusters to connect to source repo so that the hub cluster doesn't have to push down to (or pull from) spoke/managed clusters heavy workloads constantly. Also, if the spoke/managed cluster lost connection to the hub then the subscription will continue to be active.

**Comment by jianglu6** [comment]
Thank you for your reply, and now I understand. We will try to add a proxy to solve the problem of failing to connect.
